title: My Professional Portfolio
author: Jasmine Moore
email: jasminemoorewriting@gmail.com
LinkedIn: https://www.linkedin.com/in/jasminemoore1/

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This site has been updated in May 2024. Open for work!

# Build settings

# If you clone the Minima repo and build locally, use this setting.
theme: minima

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - writing.md
  - data.md
  - about.md

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: dark
