title: Jasmine Moore's Portfolio
description: Freelance writer experienced in immunology research and data science.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
LinkedIn:
  zip_url: https://www.linkedin.com/in/jasminemoore1/
  another_url: LinkedIn
